apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
